export const colors = {
  light: {
    mainBackground: '#ffffff',
    headerBorder: '#B2B2B2',
    headerBackground: '#FFFFFF',
    headerTintColor: '#f8f8f8',
    headerTitleColor: '#000000',
    backgroundColor: '#f8f8f8',
    borderColor: '#D6DEDF',
    defaultText: '#231f20',
    activeColor: '#1abfd1',
    disabledButton: '#B3B3B3',
    primaryColor: '#1fc7d4',
    infoColor: '#1d74f5',
    dangerColor: '#B43236',
    warningColor: '#ffbb00',
    successColor: '#0F6A4B',
    buttonText: '#ffffff',
    separatorBackground: '#DFDFDF',
    menuText: '#4D4849',
    inputActiveBorder: '#21929E',
    inputInactiveBorder: '#D2D1D1',
    inputHasValue: '#181414',
    noDataText: '#697479',
  },
  dark: {
    inputHasValue: '#181414',
    inputActiveBorder: '#21929E',
    inputInactiveBorder: '#D2D1D1',
    menuText: '#4D4849',
    mainBackground: '#ffffff',
    separatorBackground: '#DFDFDF',
    headerBorder: '#B2B2B2',
    headerBackground: '#FFFFFF',
    headerTintColor: '#f8f8f8',
    headerTitleColor: '#000000',
    backgroundColor: '#f8f8f8',
    borderColor: '#D6DEDF',
    defaultText: '#231f20',
    activeColor: '#1abfd1',
    disabledButton: '#B3B3B3',
    primaryColor: '#1fc7d4',
    infoColor: '#1d74f5',
    dangerColor: '#f5455c',
    warningColor: '#ffbb00',
    successColor: '#0F6A4B',
    buttonText: '#ffffff',
    noDataText: '#697479',
  },
};

export const themes = colors;
